version: "3.1"

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - db
    links:
      - "db:database"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - 8080:8080

  rabbitmq:
    image: rabbitmq
    restart: unless-stopped
    depends_on:
      - db
    links:
      - "db:database"
    ports:
      - 15692:15692
      - 5672:5672
