# Generated by Django 4.0.2 on 2022-02-26 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('default_value', models.IntegerField()),
                ('display_name', models.CharField(max_length=255)),
                ('hidden', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('icon_url', models.CharField(max_length=255)),
                ('icon_gray_url', models.CharField(max_length=255)),
                ('global_percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AchievementAchievers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
    ]
