# Generated by Django 4.2.2 on 2023-10-30 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("games", "0001_initial"),
        ("games", "0002_game_difficulty_percentage"),
        ("games", "0003_alter_game_difficulty_percentage"),
        ("games", "0004_achievement"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("img_icon_url", models.CharField(max_length=255)),
                ("added", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("resynchronized", models.DateTimeField(null=True)),
                ("resynchronization_required", models.BooleanField(default=True)),
                ("difficulty_percentage", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("default_value", models.IntegerField()),
                ("display_name", models.CharField(max_length=255)),
                ("hidden", models.BooleanField(default=False)),
                ("description", models.TextField()),
                ("icon_url", models.CharField(max_length=255)),
                ("icon_gray_url", models.CharField(max_length=255)),
                ("global_percentage", models.FloatField(default=0)),
                ("added", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("game", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.game")),
            ],
            options={
                "unique_together": {("name", "game")},
            },
        ),
    ]
