# Generated by Django 5.0.6 on 2024-06-08 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="achievement",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["name"]},
        ),
    ]
