# Generated by Django 4.0.2 on 2022-02-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_gameowner_rename_gameachievements_gameachievement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameowner",
            name="added",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
