# Generated by Django 4.2.2 on 2023-07-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_game_difficulty_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="difficulty_percentage",
            field=models.FloatField(null=True),
        ),
    ]
