# Generated by Django 4.2.2 on 2023-07-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0005_alter_gameachievement_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="img_logo_url",
        ),
        migrations.AlterField(
            model_name="game",
            name="resynchronization_required",
            field=models.BooleanField(default=True),
        ),
    ]
