# Generated by Django 4.2.2 on 2023-10-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0005_auto_20231030_2024"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="achievement",
            constraint=models.UniqueConstraint(fields=("game", "name"), name="unique_game_achievement"),
        ),
    ]
