# Generated by Django 5.0 on 2024-06-08 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("api_key", models.CharField(default="", max_length=32)),
                ("profile_url", models.CharField(default="", max_length=255)),
                ("avatar_small_url", models.CharField(default="", max_length=255)),
                ("avatar_medium_url", models.CharField(default="", max_length=255)),
                ("avatar_large_url", models.CharField(default="", max_length=255)),
                ("created", models.IntegerField(default=0)),
                ("added", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("resynchronized", models.DateTimeField(null=True)),
                ("resynchronization_required", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Friend",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "friend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_to_player",
                        to="players.player",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_to_friend",
                        to="players.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerGamePlaytime",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("playtime", models.PositiveIntegerField()),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="player_playtime", to="games.game"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="playtime", to="players.player"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerOwnedGame",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("playtime_forever", models.PositiveIntegerField()),
                ("completion_percentage", models.FloatField(default=0)),
                ("completed", models.DateTimeField(null=True)),
                ("last_played", models.DateTimeField(null=True)),
                ("added", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("resynchronized", models.DateTimeField(null=True)),
                ("resynchronization_required", models.BooleanField(default=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="owners", to="games.game"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="games", to="players.player"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerUnlockedAchievement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("datetime", models.DateTimeField()),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="unlocked_by", to="games.achievement"
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="player_achievements", to="games.game"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlocked_achievements",
                        to="players.player",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="friend",
            constraint=models.UniqueConstraint(fields=("player", "friend"), name="unique_player_friend"),
        ),
        migrations.AddConstraint(
            model_name="playerownedgame",
            constraint=models.UniqueConstraint(fields=("player", "game"), name="unique_player_game"),
        ),
        migrations.AddConstraint(
            model_name="playerunlockedachievement",
            constraint=models.UniqueConstraint(
                fields=("player", "game", "achievement"), name="unique_player_achievement"
            ),
        ),
    ]
