# Generated by Django 5.0.6 on 2024-06-08 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playerownedgame",
            options={"ordering": ["player", "game"]},
        ),
        migrations.AlterModelOptions(
            name="playerunlockedachievement",
            options={"ordering": ["player", "game"]},
        ),
    ]
