# Generated by Django 4.2.2 on 2023-07-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="games",
            field=models.ManyToManyField(
                related_name="player_games", through="players.PlayerOwnedGame", to="games.game"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="played_games",
            field=models.ManyToManyField(
                related_name="player_played_games", through="players.PlayerGamePlaytime", to="games.game"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="playergameplaytime",
            unique_together={("game", "player")},
        ),
    ]
