# Generated by Django 4.2.2 on 2023-07-20 23:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0002_player_games_player_played_games_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="playergameplaytime",
            unique_together=set(),
        ),
    ]
