# Generated by Django 5.1.4 on 2025-01-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_alter_playerownedgame_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerunlockedachievement",
            name="playtime",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
