# Generated by Django 4.2.2 on 2023-07-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0003_alter_playergameplaytime_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerownedgame",
            name="completion_percentage",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerownedgame",
            name="difficulty_percentage",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
