# Generated by Django 4.2.2 on 2023-07-23 23:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0004_playerownedgame_completion_percentage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerownedgame",
            name="difficulty_percentage",
        ),
    ]
