# Generated by Django 4.2.2 on 2023-07-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0005_remove_playerownedgame_difficulty_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerownedgame",
            name="completion_percentage",
            field=models.FloatField(default=0),
        ),
    ]
