# Generated by Django 4.2.2 on 2023-07-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0005_alter_achievementachieved_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownedgame",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
