# Generated by Django 4.2.2 on 2023-09-01 00:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "players",
            "0007_rename_achievements_resynchronization_required_playerownedgame_resynchronization_required_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="friends",
        ),
        migrations.RemoveField(
            model_name="player",
            name="games",
        ),
        migrations.RemoveField(
            model_name="player",
            name="played_games",
        ),
        migrations.RemoveField(
            model_name="player",
            name="unlocked_achievements",
        ),
    ]
