# Generated by Django 4.2.2 on 2023-09-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0008_remove_player_friends_remove_player_games_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerownedgame",
            name="last_played",
            field=models.DateTimeField(null=True),
        ),
    ]
