# Generated by Django 4.2.2 on 2023-09-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0009_playerownedgame_last_played"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerownedgame",
            name="completion_datetime",
            field=models.DateTimeField(null=True),
        ),
    ]
