# Generated by Django 4.2.2 on 2023-09-14 22:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0011_auto_20230914_2216"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playerownedgame",
            old_name="completion_datetime",
            new_name="completed",
        ),
    ]
