# Generated by Django 4.2.2 on 2023-09-25 21:46

from django.db import migrations
from loguru import logger


def set_player_game_completion_date_properly(apps, schema_editor):
    # The original implementation here was broken, so this migration didn't do anything anyway.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0012_rename_completion_datetime_playerownedgame_completed"),
    ]

    operations = [
        migrations.RunPython(set_player_game_completion_date_properly, migrations.RunPython.noop),
    ]
