# Generated by Django 4.2.2 on 2023-10-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0013_auto_20230925_2246"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="api_key",
            field=models.CharField(default="", max_length=32),
        ),
    ]
