# Generated by Django 4.2.2 on 2023-10-18 22:18

from django.db import migrations


def set_player_game_completed_properly(apps, schema_editor):
    # This implementation was still broken... Fixed in the next data migration (hopefully)
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0013_auto_20230925_2246"),
    ]

    operations = [
        migrations.RunPython(set_player_game_completed_properly, migrations.RunPython.noop),
    ]
