# Generated by Django 4.2.2 on 2023-10-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0014_auto_20231018_2318"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="api_key",
            field=models.CharField(default="", max_length=32),
        ),
    ]
