# Generated by Django 4.2.2 on 2023-10-30 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0005_auto_20231030_2024"),
        ("players", "0017_auto_20231025_2054"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerunlockedachievement",
            name="achievement",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.achievement"),
        ),
    ]
