# Generated by Django 4.2.2 on 2023-10-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0001_squashed_0018_alter_playerunlockedachievement_achievement"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friend",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="playerownedgame",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="playerunlockedachievement",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="friend",
            constraint=models.UniqueConstraint(fields=("player", "friend"), name="unique_player_friend"),
        ),
        migrations.AddConstraint(
            model_name="playerownedgame",
            constraint=models.UniqueConstraint(fields=("player", "game"), name="unique_player_game"),
        ),
        migrations.AddConstraint(
            model_name="playerunlockedachievement",
            constraint=models.UniqueConstraint(
                fields=("player", "game", "achievement"), name="unique_player_achievement"
            ),
        ),
    ]
