# Generated by Django 4.2.2 on 2023-10-31 22:15

from django.db import migrations


def reset_player_unlocked_achievements(apps, schema_editor):
    # The change to move achievements.Achievement to games.Achievement broke the relationship
    # between PlayerUnlockedAchievements and the Achievements. There is no way to recover this
    # so the data needs to be fetched from Steam again.
    # 1. Empty the PlayerUnlockedAchievements table
    # 2. Mark every player game as requiring resyncrhonization
    # 3. Achievements will be collected as the scheduled task is executed

    PlayerUnlockedAchievement = apps.get_model("players", "PlayerUnlockedAchievement")
    PlayerOwnedGame = apps.get_model("players", "PlayerOwnedGame")

    # 1. (this can take a moment)
    for achievement in PlayerUnlockedAchievement.objects.all():
        achievement.delete()

    # 2.
    for owned_game in PlayerOwnedGame.objects.all():
        owned_game.resynchronization_required = True
        owned_game.save()


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0019_alter_friend_unique_together_and_more"),
    ]

    operations = [migrations.RunPython(reset_player_unlocked_achievements, migrations.RunPython.noop)]
