# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev15+gb8bcb4b.d20230623'
__version_tuple__ = version_tuple = (0, 1, 'dev15', 'gb8bcb4b.d20230623')
