# Generated by Django 4.2.2 on 2023-07-11 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("default_value", models.IntegerField()),
                ("display_name", models.CharField(max_length=255)),
                ("hidden", models.BooleanField(default=False)),
                ("description", models.TextField()),
                ("icon_url", models.CharField(max_length=255)),
                ("icon_gray_url", models.CharField(max_length=255)),
                ("global_percentage", models.FloatField(null=True)),
                ("added", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("game", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.game")),
            ],
            options={
                "unique_together": {("name", "game")},
            },
        ),
    ]
