# Generated by Django 4.2.2 on 2023-07-07 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                ("name", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("default_value", models.IntegerField()),
                ("display_name", models.CharField(max_length=255)),
                ("hidden", models.BooleanField(default=False)),
                ("description", models.TextField()),
                ("icon_url", models.CharField(max_length=255)),
                ("icon_gray_url", models.CharField(max_length=255)),
                ("global_percentage", models.FloatField(null=True)),
                ("resynchronized", models.DateTimeField(null=True)),
                ("resynchronization_required", models.BooleanField(default=True)),
                ("game", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.game")),
            ],
        ),
    ]
