# Generated by Django 4.0.2 on 2022-02-26 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0002_rename_friends_friend"),
        ("achievements", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AchievementAchievers",
            new_name="AchievementAchiever",
        ),
    ]
