# Generated by Django 4.2.2 on 2023-10-30 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0002_alter_achievement_global_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deprecated_achievement_to_game",
                to="games.game",
            ),
        ),
    ]
