# Generated by Django 4.0.2 on 2022-02-28 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0002_rename_achievementachievers_achievementachiever"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AchievementAchiever",
        ),
    ]
