# Generated by Django 4.2.2 on 2023-10-30 22:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0003_alter_achievement_game"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Achievement",
        ),
    ]
