from .game_complete import DOCUMENT as GAME_COMPLETE_DOCUMENT
from .player import DOCUMENT as PLAYER_DOCUMENT
from .player_available_achievements import DOCUMENT as PLAYER_AVAILABLE_ACHIEVEMENTS_DOCUMENT
from .player_games import DOCUMENT as PLAYER_GAMES_DOCUMENT
from .player_perfect_games import DOCUMENT as PLAYER_PERFECT_GAMES_DOCUMENT
from .player_profile import DOCUMENT as PLAYER_PROFILE_DOCUMENT
from .player_unlocked_achievements import DOCUMENT as PLAYER_UNLOCKED_ACHIEVEMENTS_DOCUMENT
from .search import DOCUMENT as SEARCH_DOCUMENT
from .search_players import DOCUMENT as SEARCH_PLAYERS_DOCUMENT

__all__ = [
    "GAME_COMPLETE_DOCUMENT",
    "PLAYER_DOCUMENT",
    "PLAYER_AVAILABLE_ACHIEVEMENTS_DOCUMENT",
    "PLAYER_GAMES_DOCUMENT",
    "PLAYER_PERFECT_GAMES_DOCUMENT",
    "PLAYER_PROFILE_DOCUMENT",
    "PLAYER_UNLOCKED_ACHIEVEMENTS_DOCUMENT",
    "SEARCH_DOCUMENT",
    "SEARCH_PLAYERS_DOCUMENT",
]
