# Generated by Django 4.0.2 on 2022-02-28 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_delete_achievementachiever'),
        ('games', '0004_alter_game_resynchronized_delete_gameowner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameachievement',
            unique_together={('game', 'achievement')},
        ),
    ]
