# Generated by Django 4.0.2 on 2022-02-28 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_delete_achievementachiever'),
        ('games', '0005_alter_gameachievement_unique_together'),
        ('players', '0004_ownedgame_gameplaytime_achievementachieved'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='achievementachieved',
            unique_together={('achievement', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('player', 'friend')},
        ),
        migrations.AlterUniqueTogether(
            name='ownedgame',
            unique_together={('game', 'player')},
        ),
    ]
