mock_vanity_response = {"response": {"steamid": "10000000000000001", "success": 1}}

mock_player_summary = {
    "steamid": "1",
    "communityvisibilitystate": 0,
    "profilestate": 0,
    "personaname": "testName",
    "profileurl": "testURL",
    "avatar": "testAvatarS",
    "avatarmedium": "testAvatarM",
    "avatarfull": "testAvatarL",
    "avatarhash": "hash",
    "lastlogoff": 0,
    "personastate": 0,
}

mock_player_owned_games = {
    "response": {
        "game_count": 8,
        "games": [
            {
                "appid": 1900,
                "name": "Earth 2160",
                "playtime_forever": 0,
                "img_icon_url": "0a721907de90582dd4a53b55a2f260df19e2c72b",
                "playtime_windows_forever": 0,
                "playtime_mac_forever": 0,
                "playtime_linux_forever": 0,
                "rtime_last_played": 0,
                "playtime_disconnected": 726,
            },
            {
                "appid": 2100,
                "name": "Dark Messiah of Might & Magic Single Player",
                "playtime_forever": 0,
                "img_icon_url": "5a08cd17d14ccb07a14f316dfa222b18a20960fd",
                "playtime_windows_forever": 0,
                "playtime_mac_forever": 0,
                "playtime_linux_forever": 0,
                "rtime_last_played": 0,
                "playtime_disconnected": 726,
            },
            {
                "appid": 2130,
                "name": "Dark Messiah of Might & Magic Multi-Player",
                "playtime_forever": 0,
                "img_icon_url": "5a08cd17d14ccb07a14f316dfa222b18a20960fd",
                "playtime_windows_forever": 0,
                "playtime_mac_forever": 0,
                "playtime_linux_forever": 0,
                "rtime_last_played": 0,
                "playtime_disconnected": 726,
            },
            {
                "appid": 3920,
                "name": "Sid Meier's Pirates!",
                "playtime_forever": 0,
                "img_icon_url": "eeb9384067131b98cd71308aeded180dd9538951",
                "playtime_windows_forever": 0,
                "playtime_mac_forever": 0,
                "playtime_linux_forever": 0,
                "rtime_last_played": 0,
                "playtime_disconnected": 726,
            },
            {
                "appid": 4000,
                "name": "Garry's Mod",
                "playtime_forever": 0,
                "img_icon_url": "4a6f25cfa2426445d0d9d6e233408de4d371ce8b",
                "has_community_visible_stats": True,
                "playtime_windows_forever": 0,
                "playtime_mac_forever": 0,
                "playtime_linux_forever": 0,
                "rtime_last_played": 0,
                "playtime_disconnected": 726,
            },
            {
                "appid": 6200,
                "name": "Ghost Master",
                "playtime_forever": 0,
                "img_icon_url": "62ed0cd5d69d7dc5cedefd92c10e30afa4a0e5f8",
                # playtime is only available if the player is the API key owner
            },
            {
                "appid": 320,
                "name": "Half-Life 2: Deathmatch",
                "playtime_forever": 72,
                "img_icon_url": "795e85364189511f4990861b578084deef086cb1",
                "playtime_windows_forever": 0,
                "playtime_mac_forever": 0,
                "playtime_linux_forever": 0,
                "rtime_last_played": 86400,
                "playtime_disconnected": 726,
            },
            {
                "appid": 340,
                "name": "Half-Life 2: Lost Coast",
                "playtime_forever": 0,
                "img_icon_url": "795e85364189511f4990861b578084deef086cb1",
                "playtime_windows_forever": 0,
                "playtime_mac_forever": 0,
                "playtime_linux_forever": 0,
                "rtime_last_played": 0,
                "playtime_disconnected": 726,
            },
            {
                "appid": 244850,
                "name": "Space Engineers",
                "playtime_2weeks": 432,
                "playtime_forever": 22569,
                "img_icon_url": "f9856a90000d88e9a89441a7381fe9877e91eaca",
                "has_community_visible_stats": True,
                "playtime_windows_forever": 4334,
                "playtime_mac_forever": 0,
                "playtime_linux_forever": 0,
                "rtime_last_played": 1688516620,
                "playtime_disconnected": 726,
            },
        ],
    }
}
