name: ❓Check Style

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3

    - name: Install Dependencies
      run: |
        python -m pip install pip build --upgrade
        pip install .[dev]

    - name: Check Style
      run: python -m ruff check ./src