name: ❓Check Backend

on:
  pull_request:

jobs:
  formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Check Formatting
        run: uv run ruff format --check

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Check Style
        run: uv run ruff check ./src

  test:
    runs-on: ubuntu-latest
    container: python:3.12.8-bookworm

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install Dependencies
        run: uv sync --all-groups

      - name: Test
        working-directory: src/
        env:
          PGHOST: postgres
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: postgres
          # Actual key is not required for tests
          STEAM_API_KEY: ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEF
        run: uv run manage.py test

      - name: pytest
        working-directory: tests/
        env:
          # Actual key is not required for tests
          STEAM_API_KEY: ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEF
        run: uv run pytest --maxfail=1 --disable-warnings -q
