name: ❓Check Linting

on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install Dependencies
        run: |
          python -m pip install pip build --upgrade
          pip install .[dev]

      - name: Check Style
        run: python -m ruff check ./src

  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3

      - name: Install Dependencies
        working-directory: ui
        run: npm ci

      - name: Build
        working-directory: ui
        run: npm run lint
