name: 🔬 Run Tests

on:
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install Dependencies
        run: |
          python -m pip install pip build --upgrade
          pip install .[dev]

      - name: Start postgresql
        env:
          POSTGRES_PASSWORD: password
        run: |
          sudo systemctl start postgresql.service
          pg_isready

      - name: Run Tests
        working-directory: src/
        run: python manage.py test

  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3

      - name: Install Dependencies
        working-directory: ui
        run: npm ci

      - name: Build
        working-directory: ui
        run: npm run test
